### ISSUE TITLE
New Block of logging data - request

### ISSUE THREAD

**Issue by andibaciu** [just-oblivious/vindstyrka-docs#1]
Hello,
i have one request - Can you put an block of logging data but with temp and humidity varying (let's say use an hairdryer) and maybe we can see something with magical word ....
Without a direct specification from sensirion is hard to find the link between magical word and temp/humidity (if there is one).

Thank You!

**Comment by andibaciu** [comment]
Hello,
I made some assumptions about the MYSTERY WORD...
You have all the data and explanations in the attached xls file.
The data are exactly from your logs, for which I thank you once again.
All the best!

[sen5x_logging_data.xlsx](https://github.com/just-oblivious/vindstyrka-docs/files/14178067/sen5x_logging_data.xlsx)

**Comment by just-oblivious** [comment]
Unfortunately I've not been able to invest more time on the VINDSTYRKA project.
